apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: mgufronefendi@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-issuer
    solvers:
      # example: cross-account zone management for example.com
      # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
      # to assume a role in a different account
      - selector:
          dnsZones:
            - "mgufrone.xyz"
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z04414441LMS2TI908NE5
      - selector:
          dnsZones:
            - "mgufrone.dev"
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z02711982PWNXE180ECIV
      - selector:
          dnsZones:
            - "mgufron.com"
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z08831231G9YFOYHKQMW5
