{
 "title": "Application Analyzer",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Log",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handling_seconds_sum{}[5m])) by (grpc_service, grpc_method) > 0)/(sum(rate(grpc_server_started_total{}[5m])) by (grpc_service, grpc_method)>0)\n\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    },
    {}
   ]
  },
  {
   "title": "GRPC RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{}[5m])) by (grpc_service, grpc_method) > 0\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"production\"} | logfmt | __error__=\"\" and system=\"grpc\" and grpc_method!=\"Check\" | line_format \"{{.app_name}}/{{.grpc_service}}/{{.grpc_method}} [{{.grpc_code}}] {{.grpc_time_ms}}ms\""
    }
   ]
  },
  {
   "title": "Verbose Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"production\"} | logfmt "
    }
   ]
  },
  {
   "title": "Version Distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"production\"} | logfmt | app_name != \"\" and __error__=\"\" and grpc_method!=\"Check\"[5m])) by (version, app_name)",
     "legendFormat": "{{app_name}}/{{version}}"
    }
   ]
  },
  {
   "title": "Version Distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"production\"} | logfmt | __error__=\"\" and system=\"grpc\" and grpc_method!=\"Check\"[5m])) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Worker Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{namespace=\"production\"} | logfmt | app_name !=\"\" |app_name!=\"data-processor-data_process_tunnel\" | app_name!=\"job-service\" | pattern \"<type>: <log>\" | line_format \"{{.log}}\" | logfmt | __error__=\"\" | line_format \"[{{.level}}] ({{.app_name}}/{{.version}}) {{.msg}}\""
    }
   ]
  },
  {
   "title": "Error Stats",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "{namespace=\"production\"} | logfmt | level=\"error\" | line_format \"({{.time}}) [{{.level}}] {{.msg}}\""
    }
   ]
  },
  {
   "title": "Data Processor Tunnel",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{namespace=\"production\"} | logfmt | level=\"info\" | line_format \"{{.body}}\" | json | __error__=\"\" | line_format \"[{{.level}}] ({{.In_role}}) {{.msg}} [{{.In_source}}/{{.In_job_url}}]\""
    }
   ]
  },
  {
   "title": "General Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{namespace=\"production\"} | logfmt | level !=\"\" | line_format \"({{.time}}) [{{.job}}/{{.level}}] {{.msg}}\""
    }
   ]
  }
 ]
}